name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite assets (Laravel production build)
        run: |
          NODE_ENV=production npm run build
          echo "✅ Build completed, contents of /public/build:"
          ls -la public/build

      # Optional: Deploy or upload build folder here
      # - name: Deploy to server
      #   run: rsync -avz public/build/ user@server:/path/to/public/build/
